# Generated by Django 5.1.3 on 2025-02-13 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_shop',
            old_name='shop_photo',
            new_name='shop_license',
        ),
        migrations.RenameField(
            model_name='tbl_shop',
            old_name='shop_proof',
            new_name='shop_logo',
        ),
    ]
