# Generated by Django 5.1.3 on 2025-02-13 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_rename_shop_photo_tbl_shop_shop_license_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_shop',
        ),
    ]
