# Generated by Django 5.1.3 on 2025-02-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=50)),
                ('work_photo', models.FileField(upload_to='Assets/shop/photo/')),
                ('work_details', models.CharField(max_length=50)),
            ],
        ),
    ]
