# Generated by Django 5.1.3 on 2025-02-13 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0002_tbl_gallery_alter_tbl_work_work_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_gallery',
        ),
    ]
