# Generated by Django 5.1.3 on 2025-02-13 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0004_tbl_gallery'),
        ('Guest', '0014_delete_tbl_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_gallery',
            name='designer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_designer'),
        ),
    ]
