# Generated by Django 5.1.3 on 2025-02-27 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_tbl_stock'),
        ('User', '0006_delete_tbl_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_stock',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='tbl_product',
        ),
        migrations.DeleteModel(
            name='tbl_stock',
        ),
    ]
