# Generated by Django 5.1.3 on 2025-03-05 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_subcat'),
        ('Shop', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_product',
            name='category_id',
        ),
        migrations.AddField(
            model_name='tbl_product',
            name='subcategory_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subcat'),
            preserve_default=False,
        ),
    ]
