# Generated by Django 5.1.3 on 2025-03-05 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_remove_tbl_product_category_id_and_more'),
        ('User', '0010_delete_tbl_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_stock',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='tbl_product',
        ),
        migrations.DeleteModel(
            name='tbl_stock',
        ),
    ]
