# Generated by Django 5.1.3 on 2025-03-05 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0009_tbl_subcat'),
        ('Shop', '0006_remove_tbl_stock_product_id_delete_tbl_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_details', models.CharField(max_length=50)),
                ('product_price', models.CharField(max_length=50)),
                ('product_photo', models.FileField(upload_to='Assets/shop/photo/')),
                ('subcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subcat')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.CharField(max_length=50)),
                ('stock_date', models.DateField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.tbl_product')),
            ],
        ),
    ]
