# Generated by Django 5.1.3 on 2025-01-16 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0005_tbl_place'),
        ('Guest', '0002_delete_tbl_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_address', models.CharField(max_length=50)),
                ('user_contact', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_photo', models.FileField(upload_to='Assets/user/photo/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
