# Generated by Django 5.1.3 on 2025-01-16 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_user_delete_tbl_reg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
