# Generated by Django 5.1.3 on 2025-01-30 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_place'),
        ('Guest', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer_name', models.CharField(max_length=50)),
                ('designer_email', models.CharField(max_length=50)),
                ('designer_address', models.CharField(max_length=50)),
                ('designer_contact', models.CharField(max_length=50)),
                ('designer_password', models.CharField(max_length=50)),
                ('designer_photo', models.FileField(upload_to='Assets/designer/photo/')),
                ('designer_proof', models.FileField(upload_to='Assets/designer/photo/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
