# Generated by Django 5.1.3 on 2025-01-30 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_place'),
        ('Guest', '0007_tbl_designer'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=50)),
                ('shop_email', models.CharField(max_length=50)),
                ('shop_address', models.CharField(max_length=50)),
                ('shop_contact', models.CharField(max_length=50)),
                ('shop_password', models.CharField(max_length=50)),
                ('shop_photo', models.FileField(upload_to='Assets/shop/photo/')),
                ('shop_proof', models.FileField(upload_to='Assets/shop/photo/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
