# Generated by Django 5.1.3 on 2025-02-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_tbl_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_shop',
            name='shop_status',
            field=models.IntegerField(default=0),
        ),
    ]
