# Generated by Django 5.1.3 on 2025-02-13 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0010_tbl_designer_designer_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_shop',
        ),
    ]
