# Generated by Django 5.1.3 on 2025-02-13 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_delete_tbl_shop'),
        ('Guest', '0011_delete_tbl_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=50)),
                ('shop_email', models.CharField(max_length=50)),
                ('shop_address', models.CharField(max_length=50)),
                ('shop_contact', models.CharField(max_length=50)),
                ('shop_password', models.CharField(max_length=50)),
                ('shop_logo', models.FileField(upload_to='Assets/shop/photo/')),
                ('shop_license', models.FileField(upload_to='Assets/shop/photo/')),
                ('shop_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
