# Generated by Django 5.1.3 on 2025-02-13 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0013_tbl_work'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_work',
        ),
    ]
