# Generated by Django 5.1.3 on 2025-02-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_title', models.CharField(max_length=50)),
                ('feedback_content', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
