# Generated by Django 5.1.3 on 2025-02-20 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_tbl_feedback_delete_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_feedback',
            name='feedback_title',
        ),
    ]
