# Generated by Django 5.1.3 on 2025-02-20 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0014_delete_tbl_work'),
        ('User', '0003_remove_tbl_feedback_feedback_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_amount', models.CharField(max_length=50)),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('booking_todate', models.DateField()),
                ('booking_status', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
