# Generated by Django 5.1.3 on 2025-02-27 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_tbl_stock'),
        ('User', '0004_tbl_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_booking',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_booking',
            name='booking_todate',
        ),
        migrations.AlterField(
            model_name='tbl_booking',
            name='booking_amount',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='tbl_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_qty', models.IntegerField(default=1)),
                ('cart_status', models.IntegerField(default=0)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_booking')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.tbl_product')),
            ],
        ),
    ]
