# Generated by Django 5.1.3 on 2025-02-27 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_rename_user_id_tbl_booking_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_cart',
        ),
    ]
